In [4]:
import numpy as np
lst = [1, 2, 3, 4]
arr = np.array(lst)


In [9]:
print(arr.size)


4


In [10]:
print(arr.shape)


(4,)


In [11]:

print(arr[:3])


[1 2 3]


In [12]:
print(np.zeros(5))


[0. 0. 0. 0. 0.]


In [13]:
print(np.ones(5))

[1. 1. 1. 1. 1.]
